services:
  qemu:
    container_name: qemu
    image: qemux/qemu-docker
    environment:
      DISK_SIZE: "18G"
      RAM_SIZE: "4G"
      CPU_CORES: "1"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m
